### ISSUE TITLE
add commands suppport pls

### ISSUE THREAD

**Issue by BLAST1718** [Hebbinkpro/MagicCrates#1]

**Comment by BLAST1718** [comment]
pls

**Comment by Hebbinkpro** [comment]
Which commands should be supported?

**Comment by BLAST1718** [comment]
like u can do /minions miner {player} soif a player won that item they get minions

**Comment by Hebbinkpro** [comment]
Minions?

**Comment by BLAST1718** [comment]
all commands from plugins maybe??

**Comment by BLAST1718** [comment]
also u dev for free?

**Comment by Hebbinkpro** [comment]
I'm not going to add commands that nobody else is going to use.

If you want to contact me about plugins/commands you want contact me on discord, Hebbinkpro#5736

**Comment by Mohagames205** [comment]
@Hebbinkpro What he wants is that you can win commands. So the player can win x item and a command will be executed.

**Comment by Hebbinkpro** [comment]
Ah now i understand😅. I'm going to work on that

**Comment by Hebbinkpro** [comment]
Added command support
