### ISSUE TITLE
Crate key command not working 

### ISSUE THREAD

**Issue by pmmptr** [Hebbinkpro/MagicCrates#25]
![Screenshot_13](https://github.com/Hebbinkpro/MagicCrates/assets/155843589/903d8c1b-5bf9-4049-92d8-cce6f098b8bb)

**Comment by Hebbinkpro** [comment]
Thanks for reporting the bug

**Comment by pmmptr** [comment]
I kindly ask you to fix it as soon as possible. It is a plugin that I enjoy using :)

**Comment by Hebbinkpro** [comment]
That's nice to hear.
I will try to release a fix for it today or tomorrow.

**Comment by pmmptr** [comment]
thanks :)

**Comment by Hebbinkpro** [comment]
Fixed, you can download the plugin on [Poggit CI](https://poggit.pmmp.io/ci/Hebbinkpro/MagicCrates/MagicCrates/49), it can take a while until it shows up on poggit releases.
