### ISSUE TITLE
Keyall Command

### ISSUE THREAD

**Issue by ParadoxPlays** [Hebbinkpro/MagicCrates#26]
I want to suggest a keyall argument. Currently you can only give a key to one palyer at a time, you could add a argument for the player that allows you to give a key to everyone online (if that's possible, idk).

Example: Instead of for instance doing /mc or /magiccrates key common 1 {player name}, you could do /mc or /magiccrates key common 1 all or make a new command such as /mc or /magiccrates keyall common 1.
I personally think this would be a nice addition as currently MagicCrates to my knowldege offers no way to give everyone online a key without having to type out everyones names individually.

**Comment by Hebbinkpro** [comment]
Thanks for the suggestion, it is possible to do this. I will include it in the next release.

**Comment by Hebbinkpro** [comment]
Implemented in v3.0.0
