### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ParadoxPlays** [Hebbinkpro/MagicCrates#28]
![Screenshot_20240222_202109_Chrome](https://github.com/Hebbinkpro/MagicCrates/assets/99149310/c22ed9f5-bdc5-498b-8170-90a3ad127dc2)
![Screenshot_20240222_202119_Chrome](https://github.com/Hebbinkpro/MagicCrates/assets/99149310/5b5cff4e-f1d3-4998-8147-2b6a0b7e54a4)

**Comment by Hebbinkpro** [comment]
Which version of the plugin are you using?
