### ISSUE TITLE
[Suggestion] One Time Rewards

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [Hebbinkpro/MagicCrates#3]
Can you make it where if someone claims one of the items the player cannot claim it again. This is very helpful for Hub servers with Cosmetics, or when you have a rank in a crate. This should be an optional thing that you can set in the config/form!

**Comment by Hebbinkpro** [comment]
Yes that's a good idea, i'm going to work on that

**Comment by ZZWILLIAMXXTrue** [comment]
Also I noticed a change(?) feature, did you mean chance, like the chance to get an item?

**Comment by Hebbinkpro** [comment]
Yes, the change is the chance to get an item. It doesn't matter how big the changes (together) are.

**Comment by Hebbinkpro** [comment]
Implemented in v3.0.0
