### ISSUE TITLE
[Suggestion] Command Rewards

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [Hebbinkpro/MagicCrates#4]
Command Rewards! When you get a reward a the console does a command.

**Comment by Hebbinkpro** [comment]
This is already supported

**Comment by ZZWILLIAMXXTrue** [comment]
How would you put it into the reward?

**Comment by ZZWILLIAMXXTrue** [comment]
Im talking about adding an option where that reward has a specific command that no other rewards have

**Comment by Hebbinkpro** [comment]
I haven't maked that yet, but i will make it when i have some time
