### ISSUE TITLE
[Suggestion] 10x Easier Crate Creation & Alias

### ISSUE THREAD

**Issue by ZZWILLIAMXXTrue** [Hebbinkpro/MagicCrates#6]
### Alias
Instead of having to right, /magiccrates, make it easier with, /mc, or /mcs. But still keep /magiccrates!

### Crate Creation
This is **not** adding the crate into the game. This is creating the crate into the game. What I mean by it is when you do /magiccrates edit, you can choose a different subcommand, it opens up a menu showing three options. It'll also kinda remove the purpose of config.yml, but keep it for data storing I guess!
**First Option**
Creating a crate, this will make it where a crate is created, once clicked it'll open up a text thingy telling you what the name of the crate should be, with color code support.
**Second Option**
Deleting a crate, this will make it where a crate is removed, once clicked it'll show all the crates in order from how it is in the config.yml. If you click one of the options, it'll it, "Are you sure you want to remove, (crate)", with a yes and no option. If click yes, it'll remove that crate and all the in-game crates that are connected to that crate.
**Third Option**
Editing a crate, this will make it where a crate is edited, once clicked it'll show all the crates in order from how it is in the config.yml. If you click one of the options it'll open up another three more options, **Name**, is where you can edit the name and the text of the crate. **Add Reward** Where you can add a reward, would also be nice if you can add a reward from your inventory. **Add Command** will add a command from the bottom thingy.

You can also add option one and two into three and make it where you have to do /magiccrates edit (crate) to save you some time!

**Comment by Hebbinkpro** [comment]
About the alias, there is an alias that you can use, /mc

About the crate type creator, i can make this but i think that it's easier to create/edit/remove crate types in the config, because if you want to add an item you need the id/meta for it, and the most people don't know the item id's so they need to search it.
Also it cost a lot of time for me to make this a good functional system

**Comment by ZZWILLIAMXXTrue** [comment]
Yeah, I was also thinking it'll cost a lot of time for you to make it...
